config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get :search, to: 'search#search'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  concern :voteble do
    member do
      patch :vote_up
      patch :vote_down
      delete :unvote
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: %i[voteble commentable] do
    resources :answers, concerns: %i[voteble commentable], shallow: true, only: %i[create destroy update] do
      patch :mark_as_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit]
      end
    end
  end

  resources :attachments,   only: :destroy
  resources :links,         only: :destroy
  resources :rewards,       only: :index
  resources :subscriptions, only: %i[create destroy]

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable
  include Commentable
  include Subscribeable
  include Linkable

  has_one :reward, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many_attached :files

  accepts_nested_attributes_for :links,  reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  belongs_to :best_answer, class_name: 'Answer', optional: true
  belongs_to :user

  validates :title, :body, presence: true

  after_create :create_subscription

  def subscribed?(user)
    subscriptions.exists?(user: user)
  end

  def find_user_subscription(user)
    subscriptions.find_by(user: user)
  end

  private

  def create_subscription
    subscriptions.create(user_id: user_id)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < BaseController
      before_action :question, except: :create

      authorize_resource

      def index
        render json: Question.all
      end

      def show
        render json: @question, serializer: QuestionSerializer
      end

      def create
        question = Question.new(question_params.merge(user: current_user))

        if question.save
          render json: question
        else
          render json: { errors: question.errors.full_messages }
        end
      end

      def update
        if @question.update(question_params)
          render json: @question
        else
          render json: { errors: @question.errors.full_messages }
        end
      end

      def destroy
        head :ok if @question.destroy
      end

      private

      def question_params
        params.require(:question).permit(:title, :body, links_attributes: %i[name url id],
                                                        reward_attributes: %i[name image])
      end

      def question
        question_id = params[:id]
        @question ||= question_id ? Question.with_attached_files.find(question_id) : Question.new
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_best_and_other_answers, only: :show
  after_action  :publish_question, only: :create

  include Voted

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new

    gon.question_id = question.id
    gon.current_user_id = current_user&.id
  end

  def new
    question.links.new
    Reward.new(question: question)
  end

  def create
    @question = Question.new(question_params.merge(user_id: current_user.id))
    if @question.save
      redirect_to @question, notice: 'Your question was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    return unless current_user.author_of?(question) && question.update(question_params)

    flash.now[:notice] = 'The question was updated successfully.'
  end

  def destroy
    if current_user.author_of?(question)
      question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted!'
    else
      flash[:error] = 'You are not allowed delete the answer'
      redirect_to questions_path
    end
  end

  private

  def question
    question_id = params[:id]
    @question ||= question_id ? Question.with_attached_files.find(question_id) : Question.new
  end

  def find_best_and_other_answers
    @best_answer = question.best_answer
    @other_answers = question.answers.where.not(id: question.best_answer_id)
  end

  helper_method :question

  def publish_question
    return if question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      {
        partial: ApplicationController.render(partial: 'questions/list_item', locals: { question: question }),
        question: question
      }
    )
  end

  def question_params
    params
      .require(:question)
      .permit(:title,
              :body,
              files: [],
              links_attributes: %i[name url id],
              reward_attributes: %i[name image])
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_list_item.html.slim
b = link_to question.title, question_path(question)
br

app/views/questions/_question.html.slim
= content_tag(:div, id: "question-#{question.id}")
  h1 id="question-title" = question.title
  p id="question-body" = question.body

  - if question.files.attached?
    - question.files.each do |file|
      div id="file-#{file.id}"
        = link_to file.filename.to_s, url_for(file)
        - if current_user&.author_of?(question)
          = link_to 'Delete', attachment_path(file), method: :delete, local: false, remote: true

  - if question.links.any?
    .links
      p Links:
      ul
        - question.links.each do |link|
          div id="link-#{link.id}"
            li
              div
                = link_to link.name, link.url
                - if link.gist?
                  span data-gist-id=link.id
                  javascript:
                    gistClient
                        .setToken("#{ENV['GITHUB_ACCESS_TOKEN']}")
                        .getOneById("#{link.gist_id}")
                        .then(response => {
                            for (const file in response.files) {
                                const current = document.querySelector('[data-gist-id="#{link.id}"]')
                                current.innerText = response.files[file].content
                            }
                        }).catch(err => console.log(err))

              - if current_user&.author_of?(link.linkable)
                = link_to 'Delete', link_path(link), method: :delete, remote: true

  .comments
    - if question.comments.any?
      p Comments:
      = render question.comments

  .subscription
    = render 'subscriptions/subscription'

  p = link_to 'Add a comment', '#', class: 'add-comment-question', data: { question_id: question.id }

  = form_with model: [question, Comment.new], local: false, class: 'hidden', html: { id: "comment-question-#{question.id}" } do |f|
    = render 'comments/form', form: f
    = f.submit 'Save'

  = render 'votes/vote', resource: question

  - if current_user&.author_of?(question)
    p = link_to 'Edit', '#', class: 'edit-question', data: { question_id: question.id }
    = link_to 'Delete', question_path(question), id: 'question-delete', method: :delete

    .question-errors
      = render 'shared/errors', resource: question

    = form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
      = f.label :title, 'Question title'
      = f.text_area :title
      = f.label :body, 'Question body'
      = f.text_area :body
      = f.label :files
      = f.file_field :files, multiple: true
      = render 'links/form', form: f

      = f.submit 'Save'

app/views/questions/index.html.slim
- if can? :create, Question
  p = link_to 'Ask question', new_question_path
.questions
  - cache collection_cache_key_for :question do
    - @questions.each do |q|
      = render 'list_item', question: q

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question, local: true do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true

  = render 'links/form',   form: f
  = render 'rewards/form', form: f
  = f.submit 'Ask'

app/views/questions/show.html.slim
.flash

- cache question do
  .question
    = render question

  .comment-errors

  .answers
    .best-answer
      - if @best_answer
        = render @best_answer, class: 'best-answer'
    .other-answers
      = render @other_answers

  .answer-errors
    = render 'shared/errors', resource: @answer

  = form_with model: [question, @answer], local: false, class: 'new-answer' do |f|
    = f.label :title, 'Answer title'
    = f.text_field :title
    = f.label :files
    = f.file_field :files, multiple: true
    = render 'links/form', form: f

    = f.submit 'Answer to question'

= javascript_pack_tag 'utilities/questions.js'
= javascript_pack_tag 'utilities/answers.js'
= javascript_pack_tag 'utilities/votes.js'

app/views/questions/update.js.erb
<% if question.errors.present? %>
  <% question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.flash').html('<%= j render "shared/flash_messages" %>');
  $('.question').html('<%= j render question %>');
  $('.edit-question').show()
  $('form#edit-question-' + '<%= j question.id %>').addClass('hidden')
<% end %>