config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get :search, to: 'search#search'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  concern :voteble do
    member do
      patch :vote_up
      patch :vote_down
      delete :unvote
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: %i[voteble commentable] do
    resources :answers, concerns: %i[voteble commentable], shallow: true, only: %i[create destroy update] do
      patch :mark_as_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit]
      end
    end
  end

  resources :attachments,   only: :destroy
  resources :links,         only: :destroy
  resources :rewards,       only: :index
  resources :subscriptions, only: %i[create destroy]

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  has_many :links, dependent: :destroy, as: :linkable
  has_many_attached :files

  belongs_to :question, touch: true
  belongs_to :user

  accepts_nested_attributes_for :links,    reject_if: :all_blank
  accepts_nested_attributes_for :comments, reject_if: :all_blank

  validates :title, presence: true

  after_create :notify_subscribers, if: :any_subscribers?

  def mark_as_best
    transaction do
      question.update(best_answer_id: id)
      question.reward&.update(user: user)
    end
  end

  def best_answer?
    question.best_answer_id == id
  end

  private

  def notify_subscribers
    NotificationJob.perform_later(self, question)
  end

  def any_subscribers?
    question.subscriptions.exists?
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :answer
  after_action :publish_answer, only: %i[create]

  include Voted

  authorize_resource

  def mark_as_best
    @old_best_answer = question.best_answer
    answer.mark_as_best if current_user.author_of?(answer.question)
  end

  def create
    @answer = question.answers.build(answer_params.merge(user_id: current_user.id))
    if @answer.save
      flash[:alert] = 'Answer successfully created!'
    else
      render nothing: true, status: :unprocessable_entity
    end
  end

  def destroy
    if current_user.author_of?(answer)
      answer.destroy
      flash[:alert] = 'Answer successfully deleted!'
    else
      flash[:error] = 'You are not allowed delete the answer'
    end
  end

  def update
    return unless current_user.author_of?(answer) && answer.update(answer_params)

    flash.now[:notice] = 'The answer was updated successfully.'
  end

  private

  def answer
    answer_id = params[:id]
    @answer ||= answer_id ? Answer.with_attached_files.find(answer_id) : Answer.new
  end

  helper_method :answer, :question

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{params[:question_id]}/answers", {
        partial: ApplicationController.render(
          partial: 'answers/non_author_answer',
          locals: { answer: @answer }
        ),
        current_user_id: current_user.id
      }
    )
  end

  def question
    Question.find(params[:question_id] || answer.question_id)
  end

  def answer_params
    params.require(:answer).permit(:title, files: [], links_attributes: %i[name url id])
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < BaseController
      before_action :find_question, only: :create
      before_action :find_answer,   only: %i[update destroy]
      authorize_resource

      def index
        @answers = Answer.where(question_id: params[:question_id])
        render json: @answers
      end

      def show
        @answer = Answer.find(params[:id])
        render json: @answer
      end

      def create
        answer = @question.answers.build(answer_params.merge(user: current_user))

        if answer.save
          render json: answer
        else
          render json: { errors: answer.errors.full_messages }
        end
      end

      def update
        if @answer.update(answer_params)
          render json: @answer
        else
          render json: { errors: @answer.errors.full_messages }
        end
      end

      def destroy
        head :ok if @answer.destroy
      end

      private

      def answer_params
        params.require(:answer).permit(:title, links_attributes: %i[name url id],
                                               reward_attributes: %i[name image])
      end

      def find_question
        @question = Question.find(params[:question_id])
      end

      def find_answer
        @answer = Answer.find(params[:id])
      end
    end
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  = content_tag(:div, id: "answer-#{answer.id}", class: 'answer')
    p = answer.title

    - if user_signed_in? && current_user&.author_of?(answer)
      p = link_to 'Edit', '#', id: "answer-edit-#{answer.id}", class: 'edit-answer-link', data: { answer_id: answer.id }

    - if answer.best_answer?
      p = 'It is the best answer!'
    - else
      - if current_user&.author_of?(question)
        = link_to 'Mark as best', mark_as_best_answer_path(answer), method: :patch, remote: true

    - if answer.files.attached?
      br
      - answer.files.each do |file|
        div id="file-#{file.id}"
          = link_to file.filename.to_s, url_for(file)
          - if current_user&.author_of?(answer)
            = link_to 'Delete', attachment_path(file), method: :delete, local: false, remote: true

    .links
      - unless answer.links.empty?
        p Links
        ul
          - answer.links.each do |link|
            div id="link-#{link.id}"
              li
                = link_to link.name, link.url
                - if current_user&.author_of?(link.linkable)
                  = link_to 'Delete', link_path(link), method: :delete, remote: true

    .comments answer-id=answer.id
      - if answer.comments.any?
        p Comments:
        = render answer.comments

    .votes
      = render 'votes/vote', resource: answer

    p = link_to 'Add a comment', '#', id: "answer-comment-#{answer.id}", class: 'add-comment-answer', data: { answer_id: answer.id }

    = form_with model: [answer, Comment.new], local: false, class: 'hidden', html: { id: "comment-answer-#{answer.id}" } do |f|
      = render 'comments/form', form: f
      = f.submit 'Save'

    = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      = f.label :title, 'Answer title'
      = f.text_area :title
      = f.label :files
      = f.file_field :files, multiple: true
      = render 'links/form', form: f

      = f.submit 'Save'

    - if current_user&.author_of?(answer)
      p id="answer-delete-#{answer.id}" = link_to 'Delete', answer_path(answer), method: :delete, remote: true

app/views/answers/_non_author_answer.html.slim
= content_tag(:div, id: "answer-#{answer.id}", class: 'answer')
  p = answer.title

  - if answer.best_answer? 
      p = 'It is the best answer!'
  
  - if answer.files.attached?
    br
    - answer.files.each do |file|
      div id="file-#{file.id}"
        = link_to file.filename.to_s, url_for(file)
  
  .links
    - unless answer.links.empty?
      p Links
      ul
        - answer.links.each do |link|
          div id="link-#{link.id}"
            li
              = link_to link.name, link.url

  .comment-errors

  .comments answer-id=answer.id
    - if answer.comments.any?
      p Comments:
      = render answer.comments

  .votes
    = render 'votes/vote', resource: answer

  p = link_to 'Add a comment', '#', id: "answer-comment-#{answer.id}", class: 'add-comment-answer', data: { answer_id: answer.id }

  = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    = f.label :title, 'Answer title'
    = f.text_area :title
    = f.label :files
    = f.file_field :files, multiple: true
    = render 'links/form', form: f

    = f.submit 'Save'

app/views/answers/create.js.erb
<% if answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_title').val('');
  $('.flash').html('<%= j render 'shared/flash_messages' %>');
<% else %>
  $('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
  $('.flash').html('<%= j render 'shared/flash_messages' %>');
<% end %>

app/views/answers/destroy.js.erb
$('.flash').html('<%= j render "shared/flash_messages"%>');

$('#answer-<%= answer.id %>').remove()

app/views/answers/mark_as_best.js.erb
<% if answer.errors.present? %>
  <% answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answer-<%= j answer.question.best_answer_id %>').html('<%= j render answer.question.best_answer %>')
  $('#answer-<%= j answer.question.best_answer_id %>').appendTo('.best-answer')
  <% unless @old_best_answer.nil? %>
    $('#answer-<%= j @old_best_answer.id %>').html('<%= j render @old_best_answer %>')
    $('#answer-<%= j @old_best_answer.id %>').appendTo('.other-answers')
  <% end %>
<% end %>

app/views/answers/update.js.erb
<% if answer.errors.present? %>
  <% answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  <% answer_id = "#answer-#{answer.id}" %>
  $('.flash').html('<%= j render "shared/flash_messages" %>');
  $('<%= answer_id %>').replaceWith('<%= j render answer %>');
  
  $('#answer-edit-' + '<%= answer.id %>').show()
  $('form#edit-answer-' + '<%= j answer.id %>').addClass('hidden')
<% end %>